import { AchievementTemplate } from '../types';

export const ACHIEVEMENT_CATALOG: AchievementTemplate[] = [
    // --- WEALTH (Net Worth Milestones) ---
    // Starting Capital is £1,000,000. Achievements start at meaningful gains.
    { id: 'wealth_0_1', title: 'Baby Steps I', description: 'Reach a Net Worth of £1,010,000 (+1%)', icon: '👶', category: 'Wealth', condition: { type: 'netWorth', value: 1010000 }, xpReward: 50, tier: 'bronze', target: 1010000 },
    { id: 'wealth_0_2', title: 'Baby Steps II', description: 'Reach a Net Worth of £1,020,000 (+2%)', icon: '👣', category: 'Wealth', condition: { type: 'netWorth', value: 1020000 }, xpReward: 50, tier: 'bronze', target: 1020000 },
    { id: 'wealth_0_3', title: 'Baby Steps III', description: 'Reach a Net Worth of £1,030,000 (+3%)', icon: '👟', category: 'Wealth', condition: { type: 'netWorth', value: 1030000 }, xpReward: 50, tier: 'bronze', target: 1030000 },
    { id: 'wealth_0_4', title: 'Baby Steps IV', description: 'Reach a Net Worth of £1,040,000 (+4%)', icon: '🏃', category: 'Wealth', condition: { type: 'netWorth', value: 1040000 }, xpReward: 50, tier: 'bronze', target: 1040000 },
    { id: 'wealth_1', title: 'In The Green', description: 'Reach a Net Worth of £1,050,000 (+5%)', icon: '🌱', category: 'Wealth', condition: { type: 'netWorth', value: 1050000 }, xpReward: 100, tier: 'bronze', target: 1050000 },
    { id: 'wealth_2', title: 'Making Moves', description: 'Reach a Net Worth of £1,100,000 (+10%)', icon: '🌿', category: 'Wealth', condition: { type: 'netWorth', value: 1100000 }, xpReward: 250, tier: 'bronze', target: 1100000 },
    { id: 'wealth_3', title: 'Quarter Way', description: 'Reach a Net Worth of £1,250,000 (+25%)', icon: '💼', category: 'Wealth', condition: { type: 'netWorth', value: 1250000 }, xpReward: 500, tier: 'silver', target: 1250000 },
    { id: 'wealth_4', title: 'Halfway Home', description: 'Reach a Net Worth of £1,500,000 (+50%)', icon: '🏦', category: 'Wealth', condition: { type: 'netWorth', value: 1500000 }, xpReward: 1000, tier: 'silver', target: 1500000 },
    { id: 'wealth_5', title: 'Doubled Up', description: 'Reach a Net Worth of £2,000,000 (+100%)', icon: '💰', category: 'Wealth', condition: { type: 'netWorth', value: 2000000 }, xpReward: 2000, tier: 'gold', target: 2000000 },
    { id: 'wealth_6', title: 'Multi-Millionaire', description: 'Reach a Net Worth of £3,000,000', icon: '💎', category: 'Wealth', condition: { type: 'netWorth', value: 3000000 }, xpReward: 3000, tier: 'gold', target: 3000000 },
    { id: 'wealth_7', title: 'High Net Worth', description: 'Reach a Net Worth of £5,000,000', icon: '🚀', category: 'Wealth', condition: { type: 'netWorth', value: 5000000 }, xpReward: 5000, tier: 'gold', target: 5000000 },
    { id: 'wealth_8', title: 'Eight Figures', description: 'Reach a Net Worth of £10,000,000', icon: '🏰', category: 'Wealth', condition: { type: 'netWorth', value: 10000000 }, xpReward: 10000, tier: 'gold', target: 10000000 },
    { id: 'wealth_9', title: 'Quarter Century', description: 'Reach a Net Worth of £25,000,000', icon: '👑', category: 'Wealth', condition: { type: 'netWorth', value: 25000000 }, xpReward: 25000, tier: 'gold', target: 25000000 },
    { id: 'wealth_10', title: 'Half Century', description: 'Reach a Net Worth of £50,000,000', icon: '🐋', category: 'Wealth', condition: { type: 'netWorth', value: 50000000 }, xpReward: 50000, tier: 'gold', target: 50000000 },
    { id: 'wealth_11', title: 'Nine Figures', description: 'Reach a Net Worth of £100,000,000', icon: '🌍', category: 'Wealth', condition: { type: 'netWorth', value: 100000000 }, xpReward: 100000, tier: 'gold', target: 100000000 },
    { id: 'wealth_12', title: 'Half Billion', description: 'Reach a Net Worth of £500,000,000', icon: '🌌', category: 'Wealth', condition: { type: 'netWorth', value: 500000000 }, xpReward: 500000, tier: 'gold', target: 500000000 },
    { id: 'wealth_13', title: 'Billionaire', description: 'Reach a Net Worth of £1,000,000,000', icon: '🦄', category: 'Wealth', condition: { type: 'netWorth', value: 1000000000 }, xpReward: 1000000, tier: 'gold', target: 1000000000 },
    { id: 'wealth_14', title: 'Multi-Billionaire', description: 'Reach a Net Worth of £5,000,000,000', icon: '🪐', category: 'Wealth', condition: { type: 'netWorth', value: 5000000000 }, xpReward: 2500000, tier: 'gold', target: 5000000000 },
    { id: 'wealth_15', title: 'Trillionaire', description: 'Reach a Net Worth of £1,000,000,000,000', icon: '👽', category: 'Wealth', condition: { type: 'netWorth', value: 1000000000000 }, xpReward: 5000000, tier: 'gold', target: 1000000000000 },

    // --- PROFIT (Realized Gains) ---
    { id: 'profit_1', title: 'Pocket Change', description: 'Make £1,000 total profit', icon: '🪙', category: 'Wealth', condition: { type: 'profit_total', value: 1000 }, xpReward: 50, tier: 'bronze', target: 1000 },
    { id: 'profit_2', title: 'Side Hustle', description: 'Make £5,000 total profit', icon: '💵', category: 'Wealth', condition: { type: 'profit_total', value: 5000 }, xpReward: 150, tier: 'bronze', target: 5000 },
    { id: 'profit_3', title: 'Salary Replacement', description: 'Make £50,000 total profit', icon: '💸', category: 'Wealth', condition: { type: 'profit_total', value: 50000 }, xpReward: 500, tier: 'silver', target: 50000 },
    { id: 'profit_4', title: 'Big Earner', description: 'Make £100,000 total profit', icon: '💰', category: 'Wealth', condition: { type: 'profit_total', value: 100000 }, xpReward: 1000, tier: 'silver', target: 100000 },
    { id: 'profit_5', title: 'Quarter Mil', description: 'Make £250,000 total profit', icon: '🏦', category: 'Wealth', condition: { type: 'profit_total', value: 250000 }, xpReward: 2500, tier: 'gold', target: 250000 },
    { id: 'profit_6', title: 'Half Mil', description: 'Make £500,000 total profit', icon: '💎', category: 'Wealth', condition: { type: 'profit_total', value: 500000 }, xpReward: 5000, tier: 'gold', target: 500000 },
    { id: 'profit_7', title: 'Million Profit', description: 'Make £1,000,000 total profit', icon: '🚀', category: 'Wealth', condition: { type: 'profit_total', value: 1000000 }, xpReward: 10000, tier: 'gold', target: 1000000 },
    { id: 'profit_8', title: 'Empire Profit', description: 'Make £10,000,000 total profit', icon: '👑', category: 'Wealth', condition: { type: 'profit_total', value: 10000000 }, xpReward: 50000, tier: 'gold', target: 10000000 },

    // --- TRADING (Activity) ---
    { id: 'trade_1', title: 'First Steps', description: 'Complete 1 trade', icon: '👶', category: 'Trading', condition: { type: 'trades', value: 1 }, xpReward: 10, tier: 'bronze', target: 1 },
    { id: 'trade_2', title: 'Getting Started', description: 'Complete 5 trades', icon: '🚶', category: 'Trading', condition: { type: 'trades', value: 5 }, xpReward: 50, tier: 'bronze', target: 5 },
    { id: 'trade_3', title: 'Active', description: 'Complete 10 trades', icon: '🏃', category: 'Trading', condition: { type: 'trades', value: 10 }, xpReward: 100, tier: 'bronze', target: 10 },
    { id: 'trade_4', title: 'Regular', description: 'Complete 25 trades', icon: '👟', category: 'Trading', condition: { type: 'trades', value: 25 }, xpReward: 250, tier: 'bronze', target: 25 },
    { id: 'trade_5', title: 'Frequent', description: 'Complete 50 trades', icon: '👞', category: 'Trading', condition: { type: 'trades', value: 50 }, xpReward: 500, tier: 'silver', target: 50 },
    { id: 'trade_6', title: 'Dedicated', description: 'Complete 100 trades', icon: '👔', category: 'Trading', condition: { type: 'trades', value: 100 }, xpReward: 1000, tier: 'silver', target: 100 },
    { id: 'trade_7', title: 'Committed', description: 'Complete 250 trades', icon: '💼', category: 'Trading', condition: { type: 'trades', value: 250 }, xpReward: 2500, tier: 'silver', target: 250 },
    { id: 'trade_8', title: 'Obsessed', description: 'Complete 500 trades', icon: '🔥', category: 'Trading', condition: { type: 'trades', value: 500 }, xpReward: 5000, tier: 'gold', target: 500 },
    { id: 'trade_9', title: 'Professional', description: 'Complete 1,000 trades', icon: '🏗️', category: 'Trading', condition: { type: 'trades', value: 1000 }, xpReward: 10000, tier: 'gold', target: 1000 },
    { id: 'trade_9_1', title: 'Grinder', description: 'Complete 1,500 trades', icon: '⚙️', category: 'Trading', condition: { type: 'trades', value: 1500 }, xpReward: 15000, tier: 'gold', target: 1500 },
    { id: 'trade_10', title: 'Veteran', description: 'Complete 2,500 trades', icon: '🎖️', category: 'Trading', condition: { type: 'trades', value: 2500 }, xpReward: 25000, tier: 'gold', target: 2500 },
    { id: 'trade_10_1', title: 'Master', description: 'Complete 3,500 trades', icon: '🥋', category: 'Trading', condition: { type: 'trades', value: 3500 }, xpReward: 35000, tier: 'gold', target: 3500 },
    { id: 'trade_11', title: 'Elite', description: 'Complete 5,000 trades', icon: '🏆', category: 'Trading', condition: { type: 'trades', value: 5000 }, xpReward: 50000, tier: 'gold', target: 5000 },
    { id: 'trade_11_1', title: 'Grandmaster', description: 'Complete 7,500 trades', icon: '👑', category: 'Trading', condition: { type: 'trades', value: 7500 }, xpReward: 75000, tier: 'gold', target: 7500 },
    { id: 'trade_12', title: 'Legendary', description: 'Complete 10,000 trades', icon: '🌟', category: 'Trading', condition: { type: 'trades', value: 10000 }, xpReward: 100000, tier: 'gold', target: 10000 },
    { id: 'trade_12_1', title: 'Mythic', description: 'Complete 15,000 trades', icon: '🦄', category: 'Trading', condition: { type: 'trades', value: 15000 }, xpReward: 150000, tier: 'gold', target: 15000 },
    { id: 'trade_13', title: 'Market Maker', description: 'Complete 25,000 trades', icon: '🏦', category: 'Trading', condition: { type: 'trades', value: 25000 }, xpReward: 250000, tier: 'gold', target: 25000 },
    { id: 'trade_13_1', title: 'Institution', description: 'Complete 35,000 trades', icon: '🏢', category: 'Trading', condition: { type: 'trades', value: 35000 }, xpReward: 350000, tier: 'gold', target: 35000 },
    { id: 'trade_14', title: 'Algo Bot', description: 'Complete 50,000 trades', icon: '🤖', category: 'Trading', condition: { type: 'trades', value: 50000 }, xpReward: 500000, tier: 'gold', target: 50000 },
    { id: 'trade_14_1', title: 'HFT', description: 'Complete 75,000 trades', icon: '⚡', category: 'Trading', condition: { type: 'trades', value: 75000 }, xpReward: 750000, tier: 'gold', target: 75000 },

    // --- MASTERY (Skill) ---
    { id: 'mastery_1', title: 'Profitable Start', description: 'Close a profitable trade', icon: '✅', category: 'Mastery', condition: { type: 'profit_trade', value: 1 }, xpReward: 50, tier: 'bronze', target: 1 },
    { id: 'mastery_2', title: 'Small Win', description: '>5% gain on a trade', icon: '📈', category: 'Mastery', condition: { type: 'gain_percent', value: 5 }, xpReward: 100, tier: 'bronze', target: 5 },
    { id: 'mastery_3', title: 'Solid Gain', description: '>10% gain on a trade', icon: '🚀', category: 'Mastery', condition: { type: 'gain_percent', value: 10 }, xpReward: 250, tier: 'bronze', target: 10 },
    { id: 'mastery_4', title: 'Big Win', description: '>20% gain on a trade', icon: '🌕', category: 'Mastery', condition: { type: 'gain_percent', value: 20 }, xpReward: 500, tier: 'silver', target: 20 },
    { id: 'mastery_5', title: 'Huge Win', description: '>50% gain on a trade', icon: '🪐', category: 'Mastery', condition: { type: 'gain_percent', value: 50 }, xpReward: 1000, tier: 'silver', target: 50 },
    { id: 'mastery_6', title: 'Double Up', description: '>100% gain on a trade', icon: '2️⃣', category: 'Mastery', condition: { type: 'gain_percent', value: 100 }, xpReward: 2500, tier: 'gold', target: 100 },
    { id: 'mastery_7', title: 'Triple Up', description: '>200% gain on a trade', icon: '3️⃣', category: 'Mastery', condition: { type: 'gain_percent', value: 200 }, xpReward: 5000, tier: 'gold', target: 200 },
    { id: 'mastery_8', title: 'Home Run', description: '>500% gain on a trade', icon: '⚾', category: 'Mastery', condition: { type: 'gain_percent', value: 500 }, xpReward: 10000, tier: 'gold', target: 500 },
    { id: 'mastery_9', title: 'Ten Bagger', description: '>1000% gain on a trade', icon: '🔟', category: 'Mastery', condition: { type: 'gain_percent', value: 1000 }, xpReward: 25000, tier: 'gold', target: 1000 },
    { id: 'mastery_10', title: 'Sniper', description: '>5% profit in <10 mins', icon: '🎯', category: 'Mastery', condition: { type: 'quick_profit', value: 5 }, xpReward: 1000, tier: 'silver', target: 5 },
    { id: 'mastery_11', title: 'Diamond Hands', description: 'Hold for 30 days & profit', icon: '💎', category: 'Mastery', condition: { type: 'hold_duration', value: 30 }, xpReward: 2000, tier: 'gold', target: 30 },
    { id: 'mastery_12', title: 'Perfect Day', description: '3 profitable trades in a row', icon: '☀️', category: 'Mastery', condition: { type: 'win_streak', value: 3 }, xpReward: 500, tier: 'bronze', target: 3 },
    { id: 'mastery_13', title: 'Perfect Week', description: '5 profitable trades in a row', icon: '🔥', category: 'Mastery', condition: { type: 'win_streak', value: 5 }, xpReward: 1000, tier: 'silver', target: 5 },
    { id: 'mastery_14', title: 'Hot Streak', description: '10 profitable trades in a row', icon: '⚡', category: 'Mastery', condition: { type: 'win_streak', value: 10 }, xpReward: 2500, tier: 'gold', target: 10 },
    { id: 'mastery_15', title: 'Unstoppable', description: '20 profitable trades in a row', icon: '🌪️', category: 'Mastery', condition: { type: 'win_streak', value: 20 }, xpReward: 5000, tier: 'gold', target: 20 },
    { id: 'mastery_16', title: 'Godlike', description: '50 profitable trades in a row', icon: '⚡', category: 'Mastery', condition: { type: 'win_streak', value: 50 }, xpReward: 25000, tier: 'gold', target: 50 },
    { id: 'mastery_17', title: 'Oracle', description: 'Win Rate > 60% (min 50 trades)', icon: '🔮', category: 'Mastery', condition: { type: 'win_rate', value: 60 }, xpReward: 5000, tier: 'gold', target: 60 },
    { id: 'mastery_18', title: 'Prophet', description: 'Win Rate > 70% (min 50 trades)', icon: '🧙', category: 'Mastery', condition: { type: 'win_rate', value: 70 }, xpReward: 10000, tier: 'gold', target: 70 },
    { id: 'mastery_19', title: 'Seer', description: 'Win Rate > 80% (min 50 trades)', icon: '👁️', category: 'Mastery', condition: { type: 'win_rate', value: 80 }, xpReward: 25000, tier: 'gold', target: 80 },

    // --- RISK (Volatility) ---
    { id: 'risk_1', title: 'Testing Waters', description: 'Hold 1 stock', icon: '💧', category: 'Risk', condition: { type: 'diversity', value: 1 }, xpReward: 10, tier: 'bronze', target: 1 },
    { id: 'risk_2', title: 'Diversifying', description: 'Hold 3 stocks', icon: '🌱', category: 'Risk', condition: { type: 'diversity', value: 3 }, xpReward: 50, tier: 'bronze', target: 3 },
    { id: 'risk_3', title: 'Portfolio', description: 'Hold 5 stocks', icon: '📁', category: 'Risk', condition: { type: 'diversity', value: 5 }, xpReward: 100, tier: 'bronze', target: 5 },
    { id: 'risk_4', title: 'Fund Manager', description: 'Hold 10 stocks', icon: '📊', category: 'Risk', condition: { type: 'diversity', value: 10 }, xpReward: 250, tier: 'silver', target: 10 },
    { id: 'risk_5', title: 'Index Fund', description: 'Hold 20 stocks', icon: '📈', category: 'Risk', condition: { type: 'diversity', value: 20 }, xpReward: 500, tier: 'silver', target: 20 },
    { id: 'risk_6', title: 'Market Wide', description: 'Hold 50 stocks', icon: '🌐', category: 'Risk', condition: { type: 'diversity', value: 50 }, xpReward: 1000, tier: 'gold', target: 50 },
    { id: 'risk_7', title: 'Concentrated', description: '>50% in 1 stock', icon: '🎯', category: 'Risk', condition: { type: 'concentration', value: 50 }, xpReward: 500, tier: 'bronze', target: 50 },
    { id: 'risk_8', title: 'All In', description: '>90% in 1 stock', icon: '🎲', category: 'Risk', condition: { type: 'concentration', value: 90 }, xpReward: 1000, tier: 'silver', target: 90 },
    { id: 'risk_9', title: 'Cash Heavy', description: '>90% Cash', icon: '💵', category: 'Risk', condition: { type: 'concentration', value: 0 }, xpReward: 100, tier: 'bronze', target: 0 },
    { id: 'risk_10', title: 'Penny Pincher', description: 'Profit from stock <£5', icon: '🦐', category: 'Risk', condition: { type: 'penny_profit', value: 1 }, xpReward: 500, tier: 'silver', target: 1 },
    { id: 'risk_11', title: 'Crypto Curious', description: 'Buy 1 Crypto', icon: '🪙', category: 'Risk', condition: { type: 'crypto_own', value: 1 }, xpReward: 100, tier: 'bronze', target: 1 },
    { id: 'risk_12', title: 'Crypto Heavy', description: '>£100k in Crypto', icon: '₿', category: 'Risk', condition: { type: 'crypto_value', value: 100000 }, xpReward: 1000, tier: 'gold', target: 100000 },
    { id: 'risk_13', title: 'High Roller', description: 'Trade >£100k value', icon: '💸', category: 'Risk', condition: { type: 'trade_size', value: 100000 }, xpReward: 1000, tier: 'silver', target: 100000 },
    { id: 'risk_14', title: 'YOLO', description: '<£100 cash remaining', icon: '🎰', category: 'Risk', condition: { type: 'low_cash', value: 100 }, xpReward: 500, tier: 'bronze', target: 100 },

    // --- RESILIENCE (Losses) ---
    { id: 'loss_1', title: 'Ouch', description: 'First Loss', icon: '🤕', category: 'Risk', condition: { type: 'loss_total', value: 1 }, xpReward: 10, tier: 'bronze', target: 1 },
    { id: 'loss_2', title: 'Learning Experience', description: 'Lose >5% on a trade', icon: '📚', category: 'Risk', condition: { type: 'loss_percent', value: 5 }, xpReward: 50, tier: 'bronze', target: 5 },
    { id: 'loss_3', title: 'Bad Call', description: 'Lose >10% on a trade', icon: '📉', category: 'Risk', condition: { type: 'loss_percent', value: 10 }, xpReward: 100, tier: 'bronze', target: 10 },
    { id: 'loss_4', title: 'Rough Day', description: 'Lose >20% on a trade', icon: '🌧️', category: 'Risk', condition: { type: 'loss_percent', value: 20 }, xpReward: 250, tier: 'silver', target: 20 },
    { id: 'loss_5', title: 'Loss Porn', description: 'Lose >50% on a trade', icon: '💀', category: 'Risk', condition: { type: 'loss_percent', value: 50 }, xpReward: 1000, tier: 'gold', target: 50 },
    { id: 'loss_6', title: 'Bag Holder', description: 'Total Loss > £10,000', icon: '🎒', category: 'Risk', condition: { type: 'loss_total', value: 10000 }, xpReward: 500, tier: 'silver', target: 10000 },
    { id: 'loss_7', title: 'Rekt', description: 'Total Loss > £100,000', icon: '💥', category: 'Risk', condition: { type: 'loss_total', value: 100000 }, xpReward: 2500, tier: 'gold', target: 100000 },
    { id: 'loss_8', title: 'Comeback Kid', description: 'Recover from <£900k to >£1M', icon: 'phoenix', category: 'Risk', condition: { type: 'comeback', value: 1000000 }, xpReward: 5000, tier: 'gold', target: 1000000 },

    // --- SECRET (Hidden) ---
    { id: 'secret_1', title: 'Night Owl', description: 'Trade between 2-5 AM', icon: '🦉', category: 'Secret', condition: { type: 'time_trade', value: 1 }, xpReward: 250, tier: 'bronze', target: 1 },
    { id: 'secret_2', title: 'Early Bird', description: 'Trade between 5-8 AM', icon: '☀️', category: 'Secret', condition: { type: 'time_trade', value: 1 }, xpReward: 250, tier: 'bronze', target: 1 },
    { id: 'secret_3', title: 'HODL', description: 'No sells for 7 days', icon: '✊', category: 'Secret', condition: { type: 'no_sell_streak', value: 7 }, xpReward: 500, tier: 'silver', target: 7 },
    { id: 'secret_4', title: 'Broke', description: 'Net Worth < £1,000', icon: '🕳️', category: 'Secret', condition: { type: 'netWorth_low', value: 1000 }, xpReward: 1000, tier: 'silver', target: 1000 },
    { id: 'secret_5', title: 'Consistency', description: '3 Day Login Streak', icon: '📅', category: 'Secret', condition: { type: 'login_streak', value: 3 }, xpReward: 150, tier: 'bronze', target: 3 },
    { id: 'secret_6', title: 'Dedicated', description: '7 Day Login Streak', icon: '🗓️', category: 'Secret', condition: { type: 'login_streak', value: 7 }, xpReward: 500, tier: 'silver', target: 7 },
    { id: 'secret_7', title: 'Habitual', description: '14 Day Login Streak', icon: '🔄', category: 'Secret', condition: { type: 'login_streak', value: 14 }, xpReward: 1000, tier: 'silver', target: 14 },
    { id: 'secret_8', title: 'Monthly', description: '30 Day Login Streak', icon: '🌙', category: 'Secret', condition: { type: 'login_streak', value: 30 }, xpReward: 2500, tier: 'gold', target: 30 },
    { id: 'secret_9', title: 'Two Months', description: '60 Day Login Streak', icon: '⏳', category: 'Secret', condition: { type: 'login_streak', value: 60 }, xpReward: 5000, tier: 'gold', target: 60 },
    { id: 'secret_10', title: 'Quarterly', description: '90 Day Login Streak', icon: '🍂', category: 'Secret', condition: { type: 'login_streak', value: 90 }, xpReward: 10000, tier: 'gold', target: 90 },
    { id: 'secret_11', title: 'Half Year', description: '180 Day Login Streak', icon: '❄️', category: 'Secret', condition: { type: 'login_streak', value: 180 }, xpReward: 25000, tier: 'gold', target: 180 },
    { id: 'secret_12', title: 'Yearly', description: '365 Day Login Streak', icon: '🎂', category: 'Secret', condition: { type: 'login_streak', value: 365 }, xpReward: 50000, tier: 'gold', target: 365 },
];
